### ISSUE TITLE
Cannot open Connection Manager

### ISSUE THREAD

**Issue by samteezy** [Bizcuit/vscode-ampscript#22]
When I try to open Connection Manager, I get a "command not found" error. I'm running Solus Linux, for what that's worth.

Running the logs on "trace" I find this:
```
[2021-04-07 18:52:15.868] [exthost] [info] ExtensionService#_doActivateExtension sergey-agadzhanov.ampscript {"startup":false,"extensionId":{"value":"sergey-agadzhanov.ampscript","_lower":"sergey-agadzhanov.ampscript"},"activationEvent":"onCommand:mcfs.open"}
[2021-04-07 18:52:15.868] [exthost] [info] ExtensionService#loadCommonJSModule file:///home/sam/.vscode/extensions/sergey-agadzhanov.ampscript-3.0.1/out/src/extension
[2021-04-07 18:52:15.874] [exthost] [error] Activating extension sergey-agadzhanov.ampscript failed due to an error:
[2021-04-07 18:52:15.884] [exthost] [error] Error: Cannot find module './folderManagers/contentBuilder'
Require stack:
- /home/sam/.vscode/extensions/sergey-agadzhanov.ampscript-3.0.1/out/src/libs/folderController.js
- /home/sam/.vscode/extensions/sergey-agadzhanov.ampscript-3.0.1/out/src/mcfsFileSystemProvider.js
- /home/sam/.vscode/extensions/sergey-agadzhanov.ampscript-3.0.1/out/src/extension.js
- /usr/share/vscode/resources/app/out/vs/loader.js
- /usr/share/vscode/resources/app/out/bootstrap-amd.js
- /usr/share/vscode/resources/app/out/bootstrap-fork.js
	at Function.Module._resolveFilename (internal/modules/cjs/loader.js:972:15)
	at Module._load (internal/modules/cjs/loader.js:848:27)
	at Function.f._load (electron/js2c/asar_bundle.js:5:12738)
	at Function.Module._load (/usr/share/vscode/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:65671:33)
	at Function.load (/usr/share/vscode/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:65526:37)
	at Function.load [as _load] (/usr/share/vscode/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:62924:37)
	at Module.require (internal/modules/cjs/loader.js:1032:19)
	at require (/usr/share/vscode/resources/app/out/vs/loader.js:760:36)
	at Object.<anonymous> (/home/sam/.vscode/extensions/sergey-agadzhanov.ampscript-3.0.1/out/src/libs/folderController.js:4:26)
	at Module._compile (/usr/share/vscode/resources/app/out/vs/loader.js:797:45)
	at Object.Module._extensions..js (internal/modules/cjs/loader.js:1173:10)
	at Module.load (internal/modules/cjs/loader.js:992:32)
	at Module._load (internal/modules/cjs/loader.js:885:14)
	at Function.f._load (electron/js2c/asar_bundle.js:5:12738)
	at Function.Module._load (/usr/share/vscode/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:65671:33)
	at Function.load (/usr/share/vscode/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:65526:37)
	at Function.load [as _load] (/usr/share/vscode/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:62924:37)
	at Module.require (internal/modules/cjs/loader.js:1032:19)
	at require (/usr/share/vscode/resources/app/out/vs/loader.js:760:36)
	at Object.<anonymous> (/home/sam/.vscode/extensions/sergey-agadzhanov.ampscript-3.0.1/out/src/mcfsFileSystemProvider.js:5:28)
	at Module._compile (/usr/share/vscode/resources/app/out/vs/loader.js:797:45)
	at Object.Module._extensions..js (internal/modules/cjs/loader.js:1173:10)
	at Module.load (internal/modules/cjs/loader.js:992:32)
	at Module._load (internal/modules/cjs/loader.js:885:14)
	at Function.f._load (electron/js2c/asar_bundle.js:5:12738)
	at Function.Module._load (/usr/share/vscode/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:65671:33)
	at Function.load (/usr/share/vscode/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:65526:37)
	at Function.load [as _load] (/usr/share/vscode/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:62924:37)
	at Module.require (internal/modules/cjs/loader.js:1032:19)
	at require (/usr/share/vscode/resources/app/out/vs/loader.js:760:36)
	at Object.<anonymous> (/home/sam/.vscode/extensions/sergey-agadzhanov.ampscript-3.0.1/out/src/extension.js:6:34)
	at Module._compile (/usr/share/vscode/resources/app/out/vs/loader.js:797:45)
	at Object.Module._extensions..js (internal/modules/cjs/loader.js:1173:10)
	at Module.load (internal/modules/cjs/loader.js:992:32)
	at Module._load (internal/modules/cjs/loader.js:885:14)
	at Function.f._load (electron/js2c/asar_bundle.js:5:12738)
	at Function.Module._load (/usr/share/vscode/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:65671:33)
	at Function.load (/usr/share/vscode/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:65526:37)
	at Function.load [as _load] (/usr/share/vscode/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:62924:37)
	at Module.require (internal/modules/cjs/loader.js:1032:19)
	at require (internal/modules/cjs/helpers.js:72:18)
	at Function.nodeRequire [as __$__nodeRequire] (/usr/share/vscode/resources/app/out/vs/loader.js:1022:24)
	at ExtHostExtensionService._loadCommonJSModule (/usr/share/vscode/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:65582:29)
	at ExtHostExtensionService._doActivateExtension (/usr/share/vscode/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:58222:22)
	at ExtHostExtensionService._activateExtension (/usr/share/vscode/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:58196:25)
	at processTicksAndRejections (internal/process/task_queues.js:97:5)
	at async Promise.all (index 0)
```

**Comment by Bizcuit** [comment]
Hi @samteezy 
Thanks for spotting this. Looks like the final build included artefacts from the old builds and this led to errors in some cases. Please check v3.0.2 that is already available in the marketplace and let me know if it works fine now. 
P.S: check new features - editing and filtering data in dataextensions and editing and running sql queries.

**Comment by samteezy** [comment]
Connection Manager now opens! I'll close this issue now. Thanks!
